({
	initCountriesPickList : function(component, event) {
		var countries = [
			{'label':'Algeria', 'value':'DZA', 'selected':'false'},
			{'label':'Andorra', 'value':'AND', 'selected':'false'},
			{'label':'Angola', 'value':'AGO', 'selected':'false'},
			{'label':'Argentina', 'value':'ARG', 'selected':'false'},
			{'label':'Aruba', 'value':'ABW', 'selected':'false'},
			{'label':'Australia', 'value':'AUS', 'selected':'false'},
			{'label':'Austria', 'value':'AUT', 'selected':'false'},
			{'label':'Bahamas', 'value':'BHS', 'selected':'false'},
			{'label':'Bahrain', 'value':'BHR', 'selected':'false'},
			{'label':'Barbados', 'value':'BRB', 'selected':'false'},
			{'label':'Belarus', 'value':'BLR', 'selected':'false'},
			{'label':'Belgium', 'value':'BEL', 'selected':'false'},
			{'label':'Belize', 'value':'BLZ', 'selected':'false'},
			{'label':'Benin', 'value':'BEN', 'selected':'false'},
			{'label':'Bermuda', 'value':'BMU', 'selected':'false'},
			{'label':'Bolivia', 'value':'BOL', 'selected':'false'},
			{'label':'BosniaHerzegovina', 'value':'BIH', 'selected':'false'},
			{'label':'Botswana', 'value':'BWA', 'selected':'false'},
			{'label':'Brazil', 'value':'BRA', 'selected':'false'},
			{'label':'Burkina Faso', 'value':'BFA', 'selected':'false'},
			{'label':'Burundi', 'value':'BDI', 'selected':'false'},
			{'label':'Cameroon', 'value':'CMR', 'selected':'false'},
			{'label':'Canada', 'value':'CAN', 'selected':'false'},
			{'label':'Chile', 'value':'CHL', 'selected':'false'},
			{'label':'China', 'value':'CHN', 'selected':'false'},
			{'label':'Congo', 'value':'COG', 'selected':'false'},
			{'label':'Congo, Democratic Republic', 'value':'COD', 'selected':'false'},
			{'label':'Costa Rica', 'value':'CRI', 'selected':'false'},
			{'label':'Crotia', 'value':'HRV', 'selected':'false'},
			{'label':'Cuba', 'value':'CUB', 'selected':'false'},
			{'label':'Cyprus', 'value':'CYP', 'selected':'false'},
			{'label':'Czech Republic', 'value':'CZE', 'selected':'false'},
			{'label':'Denmark', 'value':'DNK', 'selected':'false'},
			{'label':'Dominican Republic', 'value':'DOM', 'selected':'false'},
			{'label':'Ecuador', 'value':'ECU', 'selected':'false'},
			{'label':'El Salvador', 'value':'SLV', 'selected':'false'},
			{'label':'Estonia', 'value':'EST', 'selected':'false'},
			{'label':'Finland', 'value':'FIN', 'selected':'false'},
			{'label':'France', 'value':'FRA', 'selected':'false'},
			{'label':'Gabon', 'value':'GAB', 'selected':'false'},
			{'label':'Germany', 'value':'DEU', 'selected':'false'},
			{'label':'Ghana', 'value':'GHA', 'selected':'false'},
			{'label':'Greece', 'value':'GRC', 'selected':'false'},
			{'label':'Guatemala', 'value':'GTM', 'selected':'false'},
			{'label':'Guyana', 'value':'GUY', 'selected':'false'},
			{'label':'Honduras', 'value':'HND', 'selected':'false'},
			{'label':'HongKong', 'value':'HKG', 'selected':'false'},
			{'label':'Hungary', 'value':'HUN', 'selected':'false'},
			{'label':'Iceland', 'value':'ISL', 'selected':'false'},
			{'label':'India', 'value':'IND', 'selected':'false'},
			{'label':'Ireland', 'value':'IRL', 'selected':'false'},
			{'label':'Italy', 'value':'ITA', 'selected':'false'},
			{'label':'Jamaica', 'value':'JAM', 'selected':'false'},
			{'label':'Japan', 'value':'JPN', 'selected':'false'},
			{'label':'Kenya', 'value':'KEN', 'selected':'false'},
			{'label':'Kosovo', 'value':'XK1', 'selected':'false'},
			{'label':'Kuwait', 'value':'KWT', 'selected':'false'},
			{'label':'Latvia', 'value':'LVA', 'selected':'false'},
			{'label':'Lesotho', 'value':'LSO', 'selected':'false'},
			{'label':'Liechtenstein', 'value':'LIE', 'selected':'false'},
			{'label':'Lithuania', 'value':'LTU', 'selected':'false'},
			{'label':'Luxembourg', 'value':'LUX', 'selected':'false'},
			{'label':'Macau', 'value':'MAC', 'selected':'false'},
			{'label':'Macedonia', 'value':'MKD', 'selected':'false'},
			{'label':'Malawi', 'value':'MWI', 'selected':'false'},
			{'label':'Malaysia', 'value':'MYS', 'selected':'false'},
			{'label':'Mali', 'value':'MLI', 'selected':'false'},
			{'label':'Malta', 'value':'MLT', 'selected':'false'},
			{'label':'Martinique', 'value':'MTQ', 'selected':'false'},
			{'label':'Mauritius', 'value':'MUS', 'selected':'false'},
			{'label':'Maurtania', 'value':'MRT', 'selected':'false'},
			{'label':'Mexico', 'value':'MEX', 'selected':'false'},
			{'label':'Morocco', 'value':'MAR', 'selected':'false'},
			{'label':'Mozambique', 'value':'MOZ', 'selected':'false'},
			{'label':'Nambia', 'value':'NAM', 'selected':'false'},
			{'label':'Netherlands', 'value':'NLD', 'selected':'false'},
			{'label':'New Zealand', 'value':'NZL', 'selected':'false'},
			{'label':'Nicaragua', 'value':'NIC', 'selected':'false'},
			{'label':'Niger', 'value':'NER', 'selected':'false'},
			{'label':'Nigeria', 'value':'NGA', 'selected':'false'},
			{'label':'Norway', 'value':'NOR', 'selected':'false'},
			{'label':'Oman', 'value':'OMN', 'selected':'false'},
			{'label':'Panama', 'value':'PAN', 'selected':'false'},
			{'label':'Paraguay', 'value':'PRY', 'selected':'false'},
			{'label':'Peru', 'value':'PER', 'selected':'false'},
			{'label':'Phillipines', 'value':'PHL', 'selected':'false'},
			{'label':'Poland', 'value':'POL', 'selected':'false'},
			{'label':'Portugal', 'value':'PRT', 'selected':'false'},
			{'label':'Qatar', 'value':'QAT', 'selected':'false'},
			{'label':'Romania', 'value':'ROU', 'selected':'false'},
			{'label':'Russia', 'value':'RUS', 'selected':'false'},
			{'label':'Rwanda', 'value':'RWA', 'selected':'false'},
			{'label':'Saint-Kitts-and-Nevis', 'value':'KNA', 'selected':'false'},
			{'label':'Saudi-Arabia', 'value':'SAU', 'selected':'false'},
			{'label':'Senegal', 'value':'SEN', 'selected':'false'},
			{'label':'Singapore', 'value':'SGP', 'selected':'false'},
			{'label':'Slovakia', 'value':'SVK', 'selected':'false'},
			{'label':'Slovenia', 'value':'SVN', 'selected':'false'},
			{'label':'South Africa', 'value':'ZAF', 'selected':'false'},
			{'label':'Spain', 'value':'ESP', 'selected':'false'},
			{'label':'Suriname', 'value':'SUR', 'selected':'false'},
			{'label':'Swaziland', 'value':'SWZ', 'selected':'false'},
			{'label':'Sweden', 'value':'SWE', 'selected':'false'},
			{'label':'Switzerland', 'value':'CHE', 'selected':'false'},
			{'label':'Switzerland', 'value':'CHE', 'selected':'false'},
			{'label':'Taiwan', 'value':'TWN', 'selected':'false'},
			{'label':'Tanzania', 'value':'TZA', 'selected':'false'},
			{'label':'Thailand', 'value':'THA', 'selected':'false'},
			{'label':'Togo', 'value':'TGO', 'selected':'false'},
			{'label':'Trinidad-and-Tobago', 'value':'TTO', 'selected':'false'},
			{'label':'Tunisia', 'value':'TUN', 'selected':'false'},
			{'label':'Turkey', 'value':'TUR', 'selected':'false'},
			{'label':'Uganda', 'value':'UGA', 'selected':'false'},
			{'label':'United Arab Emirates', 'value':'ARE', 'selected':'false'},
			{'label':'United Kingdom', 'value':'GBR', 'selected':'false'},
			{'label':'United States', 'value':'USA', 'selected':'true'},
			{'label':'Venezuela', 'value':'VEN', 'selected':'false'},
			{'label':'Vietnam', 'value':'VNM', 'selected':'false'},
			{'label':'Zambia', 'value':'ZMB', 'selected':'false'}];

		component.set("v.countries", countries);
	},
	initMapCountries : function(){
		var countriesMap = {
			'DZA':'Algeria',
			'AND':'Andorra',
			'AGO':'Angola',
			'ARG':'Argentina',
			'ABW':'Aruba',
			'AUS':'Australia',
			'AUT':'Austria',
			'BHS':'Bahamas',
			'BHR':'Bahrain',
			'BRB':'Barbados',
			'BLR':'Belarus',
			'BEL':'Belgium',
			'BLZ':'Belize',
			'BEN':'Benin',
			'BMU':'Bermuda',
			'BOL':'Bolivia',
			'BIH':'Bosnia and Herzegovina',
			'BWA':'Botswana',
			'BRA':'Brazil',
			'BFA':'Burkina Faso',
			'BDI':'Burundi',
			'CMR':'Cameroon',
			'CAN':'Canada',
			'CHL':'Chile',
			'CHN':'China',
			'COG':'Congo',
			'COD':'Congo, Democratic Republic',
			'CRI':'Costa Rica',
			'HRV':'Crotia',
			'CUB':'Cuba',
			'CYP':'Cyprus',
			'CZE':'Czech Republic',
			'DNK':'Denmark',
			'DOM':'Dominican Republic',
			'ECU':'Ecuador',
			'SLV':'El Salvador',
			'EST':'Estonia',
			'FIN':'Finland',
			'FRA':'France',
			'GAB':'Gabon',
			'DEU':'Germany',
			'GHA':'Ghana',
			'GRC':'Greece',
			'GTM':'Guatemala',
			'GUY':'Guyana',
			'HND':'Honduras',
			'HKG':'HongKong',
			'HUN':'Hungary',
			'ISL':'Iceland',
			'IND':'India',
			'IRL':'Ireland',
			'ITA':'Italy',
			'JAM':'Jamaica',
			'JPN':'Japan',
			'KEN':'Kenya',
			'XK1':'Kosovo',
			'KWT':'Kuwait',
			'LVA':'Latvia',
			'LSO':'Lesotho',
			'LIE':'Liechtenstein',
			'LTU':'Lithuania',
			'LUX':'Luxembourg',
			'MAC':'Macau',
			'MKD':'Macedonia',
			'MWI':'Malawi',
			'MYS':'Malaysia',
			'MLI':'Mali',
			'MLT':'Malta',
			'MTQ':'Martinique',
			'MUS':'Mauritius',
			'MRT':'Maurtania',
			'MEX':'Mexico',
			'MAR':'Morocco',
			'MOZ':'Mozambique',
			'NAM':'Namibia',
			'NLD':'Netherlands',
			'NZL':'New Zealand',
			'NIC':'Nicaragua',
			'NER':'Niger',
			'NGA':'Nigeria',
			'NOR':'Norway',
			'OMN':'Oman',
			'PAN':'Panama',
			'PRY':'Paraguay',
			'PER':'Peru',
			'PHL':'Philipines',
			'POL':'Poland',
			'PRT':'Portugal',
			'QAT':'Qatar',
			'ROU':'Romania',
			'RUS':'Russia',
			'RWA':'Rwanda',
			'KNA':'Saint Kitts and Nevis',
			'SAU':'Saudi Arabia',
			'SEN':'Senegal',
			'SGP':'Singapore',
			'SVK':'Slovakia',
			'SVN':'Slovenia',
			'ZAF':'South-Africa',
			'ESP':'Spain',
			'SUR':'Suriname',
			'SWZ':'Swaziland',
			'SWE':'Sweden',
			'CHE':'Switzerland',
			'CHE':'Switzerland',
			'TWN':'Taiwan',
			'TZA':'Tanzania',
			'THA':'Thailand',
			'TGO':'Togo',
			'TTO':'Trinidad and Tobago',
			'TUN':'Tunisia',
			'TUR':'Turkey',
			'UGA':'Uganda',
			'ARE':'United Arab Emirates',
			'GBR':'United Kingdom',
			'USA':'United States',
			'VEN':'Venezuela',
			'VNM':'Viet Nam',
			'ZMB':'Zambia'
		};
		return countriesMap;
	},
	initStateProvince : function(){
		var stateProvinces = 
		{'USA':{'AL':'Alabama',
				'AK':'Alaska',
				'AZ':'Arizona',
				'AR':'Arkansas',
				'AA':'Armed Forces America',
				'AE':'Armed Forces Europe',
				'AP':'Armed Forces Pacific',
				'CA':'California',
				'CO':'Colorado',
				'CT':'Connecticut',
				'DE':'Delaware',
				'DC':'District of Columbia',
				'FL':'Florida',
				'GA':'Georgia',
				'HI':'Hawaii',
				'ID':'Idaho',
				'IL':'Illinois',
				'IN':'Indiana',
				'IA':'Iowa',
				'KS':'Kansas',
				'KY':'Kentucky',
				'LA':'Louisiana',
				'ME':'Maine',
				'MD':'Maryland',
				'MA':'Massachusetts',
				'MI':'Michigan',
				'MN':'Minnesota',
				'MS':'Mississippi',
				'MO':'Missouri',
				'MT':'Montana',
				'NE':'Nebraska',
				'NV':'Nevada',
				'NH':'New Hampshire',
				'NJ':'New Jersey',
				'NM':'New Mexico',
				'NY':'New York',
				'NC':'North Carolina',
				'ND':'North Dakota',
				'OH':'Ohio',
				'OK':'Oklahoma',
				'OR':'Oregon',
				'PA':'Pennsylvania',
				'RI':'Rhode Island',
				'SC':'South Carolina',
				'SD':'South Dakota',
				'TN':'Tennessee',
				'TX':'Texas',
				'UT':'Utah',
				'VT':'Vermont',
				'VA':'Virginia',
				'WA':'Washington',
				'WV':'West Virginia',
				'WI':'Wisconsin',
				'WY':'Wyoming'
			},
		
		'CAN':{
				'AB':'Alberta', 
				'BC':'British Columbia', 
				'MB':'Manitoba', 
				'NB':'New Brunswick', 
				'NL':'Newfoundland and Labrador', 
				'NT':'Northwest Territories', 
				'NS':'Nova Scotia', 
				'NU':'Nunavut', 
				'ON':'Ontario', 
				'PE':'Prince Edward Island', 
				'QC':'Quebec', 
				'SK':'Saskatchewan', 
				'YT':'Yukon'
			}
		};

		return stateProvinces; 
	},
	titleCase : function(str){
	   var splitStr = str.toLowerCase().split(' ');
	   for (var i = 0; i < splitStr.length; i++) {
	       // You do not need to check if i is larger than splitStr length, as your for does that for you
	       // Assign it back to the array
	       splitStr[i] = splitStr[i].charAt(0).toUpperCase() + splitStr[i].substring(1);     
	   }
	   // Directly return the joined string
	   return splitStr.join(' '); 
	}

})