/**
 * @description       : 
 * @author            : Vinayesh
 * @group             : 
 * @last modified on  : 07-19-2022
 * @last modified by  : Vinayesh
**/
public class GlobalStaticVar {
    public static boolean byPassQuoteTrigger = false;
    public static boolean byPassFreeFormEndorsementTrigger = false; 
    public static boolean byPassSubjectivityTrigger = false; 
    public static boolean byPassOpportunityTrigger = false; 
    public static boolean byPassUWAnalysisTrigger = false;
    public static boolean byPassCoverageLineItemTrigger = false;
    public static boolean byPassAPiLogTrigger = false;
    public static boolean byPassContentDocumentLinkTrigger = false;
    public static boolean byPassAccountProductTrigger = false; 
    public static boolean byPassRenewalTrigger = false;
}